=  Integration Documentation
:toc: left
:toclevels: 3
:sectanchors:
:sectlinks:
:source-indent: coderay
:icons: font


This is one in all and all in one project to integrate basic flow that is applied in all Java projects.
It supports gradle upgrades, spin up servers using docker, documenting using ascii doc, performing unit test and integration test using Junit and SpringTest.
To keep it simple, I am going to have 3 basic endpoints of capturing virtual payments using OAuth2.


.Revision History
[cols="3,1,1,1", options="header"]
|===
|change |Version |Date |By

|Initial Documentation | 1 | 2020-10-21 | Susan Grey

|===


== Gradle


.Libraries used
[cols="3,1", options="header"]
|===
|Library |Version

|SpringBoot | 2.4.0
|Gradle | 6.7.1
|SpringSecurity | 5.4.2



|===

== Docker
== Configuration
=== RestTemplateConfig
The <<RestTemplateConfig>> class configures the RestTemplate as spring bean. It adds the following custom feature -
--
 . Interceptor for logging purpose.
 . Custom error handler if needed.
 . HttpMessageConverter that can read and write JSON using Jackson 2.x's  ObjectMappe
--

.RestTemplateConfig
[[RestTemplateConfig]]
[source, java]
----
@Slf4j
@Configuration
public class RestTemplateConfig {

    @Bean
    public RestTemplate restTemplate(CustomResponseErrorHandler customResponseErrorHandler) {
        ......
    }
----

NOTE: Its uses a synchronous client to perform HTTP requests.


NOTE:
--
. As of Spring 5.0, the non-blocking, reactive org.springframework.web.reactive.client.WebClient offers a modern alternative to the RestTemplate with efficient support for both sync and async, as well as streaming scenarios.
. The RestTemplate will be deprecated in a future version and will not have major new features added going forward. See the WebClient section of the Spring Framework reference documentation for more details and example code.
--

== Security
=== OAuth2
The Spring Security OAuth project is deprecated. The latest OAuth 2.0 support is provided by Spring Security.

=== Spring Security
Spring Security is a framework that provides authentication, authorization, and protection against common attacks.

== Transaction
=== createTransaction
=== updateTransaction
=== voidTransaction
=== releaseTransaction
== Testing
=== Unit Test
=== Integration Test
